kubewarden/kubewarden.io

config.toml

Add link to slack and twitter to the top of the page.
Just a stating point, we can do something fancier later on IMHO

Add links to social spaces

---

content/blog/2021/06/introducing-the-psp-host-namespaces-policy.md

Closes https://github.com/kubewarden/kubewarden.io/issues/14

Add blog post about the `psp-host-namespaces` policy

---

content/blog/2021/07/learn-kubewarden-streaming-event.md

As per title, this fixes issue https://github.com/kubewarden/kubewarden.io/issues/18

Add blog post about streaming event done in June

---

content/blog/2021/09/towards-a-universal-policy-platform.md

Fixes https://github.com/kubewarden/kubewarden.io/issues/23
To be considered when the `opa` branch is merged in all relevant repos.

Add rego policies article

---

content/_index.html

fixes kubewarden/kubewarden.io#31

Add helm crds chart installation

---

content/blog/2021/11/deep-dive-into-policy-logging.md

Fixes: https://github.com/kubewarden/kubewarden.io/issues/22

Add policy logging blog post

---

content/blog/2022/01/policy-server-on-aarch64.md

Fixes: https://github.com/kubewarden/kubewarden.io/issues/46

Add aarch64 blog post

---

content/blog/2022/02/multiplatform-kubewarden.md

Fixes: https://github.com/kubewarden/kubewarden.io/issues/48

blog post: multi-platform kubewarden

---

layouts/partials/footer.html

Fixes: https://github.com/kubewarden/kubewarden.io/issues/57

Fix images sources

---

content/blog/2022/03/admission-policy.md

Introducing the AdmissionPolicy blog

---

content/blog/2022/03/admission-policy.md
layouts/_default/list.algolia.json
layouts/blog/single.html

Fixed a few grammatical nits and modified a few sentences for clarity.

Update Admission Policy blogpost

---

assets/sass/main.scss
layouts/partials/footer.html
layouts/partials/header.html

This fixes the issue with the mobile navigation not being styled correctly. The issue was a combination of the submodule not being updated and the custom header partial and main.scss missing the `.menu-toggle` styling. 
Fix https://github.com/rancherlabs/projects-theme/issues/4 && #30 
- Run the server with `hugo server -D`
- Open the responsive design mode in the browser (ctrl + shift + m - on firefox)
https://user-images.githubusercontent.com/40806497/163265340-0e9ee00e-b5d5-4ece-a58c-3f90629be1c7.mp4

Fix mobile menu - update theme submodule

---

assets/sass/blog-main.scss
assets/sass/blog.scss

The issue had to deal with some conflicting css classes that existed from previous editions.
Fix #80 
- `hugo server -D`

Remove a few conflicting classes - import main.scss

---

content/blog/2022/04/securing-kubewarden-policies.md

[Rendered blog here](https://github.com/viccuad/kubewarden.io/blob/sigstore-post/content/blog/2022/04/securing-kubewarden-policies.md)
Fix https://github.com/kubewarden/kubewarden.io/issues/71
Fix https://github.com/kubewarden/kubewarden.io/issues/66
Depends on: https://github.com/kubewarden/docs/pull/100
Marked as draft, missing linking to non-published docs yet.

feat: Add post "securing Kubewarden policies"

---

content/blog/2022/04/securing-kubewarden-policies.md

Addressing nits & slight rephrasing for clarity.

Addressing nits

---

content/blog/2022/05/monitor-mode.md

Fixes: https://github.com/kubewarden/kubewarden.io/issues/92

Blog post: monitor mode

---

content/blog/2022/05/psp-migration-docs.md

Updates the PSP migration blog post to the date when it got released.

Fix PSP migration blog post date.

---

content/blog/2022/05/verifying-image-signatures.md

Fix #84 
Replace https://github.com/kubewarden/kubewarden.io/pull/87

feat: add Verifying image signatures blog

---

content/blog/2022/05/verifying-image-signatures.md

this is the missing commit https://github.com/kubewarden/kubewarden.io/commit/a0ae28cf227cfff1a42cfaa4f8b39b3a76bf90b4

Add missing commit from review

---

content/_index.html

Add `helm install kubewarden-defaults` command to landing page

Add `helm install kubewarden-defaults` command to landing page

---

content/blog/2022/06/cncf-sandbox-inclusion.md

Cover the inclusion inside of CNCF

Add blog post about CNCF inclusion

---

config.toml
content/blog/2022/06/v1-release.md

Add blog post covering the v1 release. Fixes https://github.com/kubewarden/kubewarden.io/issues/103
This is currently a draft release, it's blocked by the final v1 release.
**TODO before publishing:**

V1 blog post

---

content/blog/2022/07/psp-migration-script.md

Adds a blog post about the script create to migrate PSPs to Kubewarden policies.

PSP migration script.

---

content/blog/2022/07/verify-signatures-with-gha-and-prefix.md

feat: Add verify signatures with github actions and subject prefix blog

---

content/blog/2022/07/artifact-hub-supports-kubewarden.md

This is part of this epic https://github.com/kubewarden/policy-hub/issues/190

Add blog post about Artifact Hub integration

---

content/blog/2022/07/v1.1.1-release.md

Fix https://github.com/kubewarden/kubewarden.io/issues/117
tested locally
May need bump in date.

docs: Add v1.1.1 blogpost

---

content/blog/2022/10/env-var-secrets.md

Fix https://github.com/kubewarden/kubewarden.io/issues/135

Scanning secrets in environment variables blog

---

content/blog/2022/10/kubewarden_1_3_release.md

Talk about what's new.
Fixes https://github.com/kubewarden/kubewarden.io/issues/136

Add blog post about 1.3.0 release

---

content/blog/2022/10/envvar-policy.md

Announce the new envvar policy.

---

content/blog/2022/10/volumemounts-policy.md
content/blog/2022/11/volumemounts-policy.md

Fix https://github.com/kubewarden/kubewarden.io/issues/133

Add new volumemounts-policy blogpost

---

content/blog/2022/11/deprecation-policy.md

Fix https://github.com/kubewarden/kubewarden.io/issues/147

Add deprecated-api-versions policy blogpost

---

content/blog/2022/11/airgap.md

Air gap blog

---

content/blog/2022/12/release-1_4_0.md

I think it will be worth to publish the article about certificate signature at the same time as this blog post.
What do you think?
Fixes https://github.com/kubewarden/kubewarden.io/issues/156

Introduce 1.4.0 release

---

content/blog/2022/12/community-meeting.md

Signed-off-by: Olivier Vernin <olivier.vernin@suse.com>
Add blogpost to announce the coming community meeting
Fix https://github.com/kubewarden/kubewarden-controller/issues/346
/

Announce the first community meeting

---

content/blog/2022/12/kubewarden-2022-wrapped.md

This fixes https://github.com/kubewarden/kubewarden.io/issues/164

New blog post: 2022 and Kubewarden

---

content/blog/2023/01/release-1_5_0.md

Fixes typo in release -1_5_0.md
< [Documentation](https://github.com/kubewarden/kubewarden.io/blob/main/content/blog/2023/01/release-1_5_0.md) >

Fixed typo in release-1_5_0.md

---

content/blog/2021/06/writing-your-first-policy-with-kubewarden.md

Addressing grammatical nits in writing-your-first-policy-with-kubewarden.md

Addressing grammatical nits in writing-your-first-policy-with-kubewarden.md

---

content/blog/2022/04/securing-kubewarden-policies.md

Fix typo in securing-kubewarden-policies.md

Fix typo in securing-kubewarden-policies.md

---

content/blog/2022/12/release-1_4_0.md

Fix typo in release-1_4_0

---

content/_index.html

Explain how to get in touch with us
This is how the new page looks like:

Add community calendar

---

layouts/_default/baseof.html

Attempt to defend against [clickjacking](https://cheatsheetseries.owasp.org/cheatsheets/Clickjacking_Defense_Cheat_Sheet.html).

feat: Set Content-Security-Policy frame-src self

---

layouts/_default/baseof.html

Attempt to defend against clickjacking.
Allow images, scripts, AJAX, form actions, and CSS from the same origin. Do not allow any other resources to load (eg object, frame, media, etc).
https://clickjacker.io/test?url=kubewarden.io

feat: Set minimum Content-Security-Policy

---

layouts/_default/baseof.html

The attempt didn't work, and we don't need it.

fix: Remove Content-Security-Policy

---

content/blog/2023/04/kubewarden-.1.6.0-release.md

Introduce the 1.6.0 release
This fixes https://github.com/kubewarden/kubewarden.io/issues/179
The issue tracking this blog post suggested more topics to be addressed. I tried to keep the article short to prevent attention loss; I did that by talking about the 2 major changes for our users.

New blog post: 1.6.0 release

---

content/blog/2023/05/kubewarden-telemetry-fixes-release.md

Adds a blog post about the Kubewarden release with the enhancements and fixes on the telemetry story.

Telemetry enhancements release.

---

content/blog/2023/05/khaled-mentorship-xp.md

Adds a blog post about the LFX Mentorship program experience from one of the mentees.
Fix #182

LFX Mentorship program experience

---

content/blog/2023/10/kubewarden-1.8-release.md

Relates to https://github.com/kubewarden/helm-charts/issues/310

Add 1.8.0 release blogpost

---

content/blog/2023/10/wasi-policies.md

Fixes issue #190
Not ready for review, I just want to try the new netlify integration I've enabled.
**Update:** it works :sunglasses: https://deploy-preview-191--moonlit-trifle-c6359f.netlify.app/blog/2023/09/wasi-policies/

Blog post about WASI policies

---

content/blog/2023/10/wasi-policies.md

Fix typo in wasi-policies.md

---

content/blog/2023/11/kubewarden-1.9-release.md

Add blog post about the 1.9.0 release

---

content/blog/2023/12/kubewarden-2023-wrapped.md

This fixes https://github.com/kubewarden/kubewarden.io/issues/205

New blog post: 2023 wrap up

---

layouts/partials/survey-banner.html

This removes the "Happy Holidays" mention in the survey banner.

Remove holidays mention from survey banner

---

content/blog/2024/03/kubewarden-1-11-release.md

Fixes https://github.com/kubewarden/kubewarden.io/issues/215

Blog post: introducing KW 1.11

---

content/blog/2024/04/community-repository.md

Adds a new blog post to announce the community repository.
Related to https://github.com/kubewarden/kubewarden-controller/issues/659

feat: community repository blog post

---

content/blog/2024/04/kubewarden-1-12-release.md

Fix https://github.com/kubewarden/kubewarden.io/issues/220

feat: Add blogpost for 1.12 release

---

assets/sass/blog-main.scss

Before:
After:
See the render.

feat: Add more subtle code scss for 1-line code blocks

---

content/_index.html

To be merged at the same time as #408 in docs

Manual bump version number to 1.13

---

assets/sass/blog-main.scss
content/blog/2024/06/kubewarden-1-13-release.md

This fixes https://github.com/kubewarden/kubewarden.io/issues/227
Note: I don't like how the table is rendered by hugo. I'll try to address that.

Blog post about 1.13 release

---

content/blog/2024/06/kubewarden-1-14-release.md

Adds a blog post to show what was accomplished in the v1.14 release.
Fix #235

Blog post about 1.14 release.

---

updatecli/updatecli.d/updcli-kw-ver.yml

use GITHUB_OWNER, NOT UPDCLI_GITHUB_OWNER

---

updatecli/updatecli.d/updcli-kw-ver.yml

added labels for chore and documentation

---

content/blog/2024/07/kubewarden-1-15-release.md

Adds the blog post about the v1.15 release.
Fix #243

v1.15 blog post.

---

.gitignore
updatecli/updatecli.d/updcli-kw-ver.yml

Only use the first two parts of the version number.

Only use the first two parts of the version number.

---

content/_index.html

Add link to GitHub discussions

---

content/blog/2024/08/kubewarden-1-16-release.md

Fix https://github.com/kubewarden/kubewarden.io/issues/254

Add 1.16 release post

---

content/blog/2024/09/policy-server-and-kwctl-1-16-1-patch-release.md

Cover the patch releases of policy server and kwctl

New blog post about 1.16.1 releases

---

content/blog/2024/10/kubewarden-1-17-release.md

Add trusted-repos policy to 1.17 blogpost

---

.github/workflows/updatecli.yml
updatecli/updatecli.d/updcli-kw-ver.yml
updatecli/values.yml

Add `Signed-off-by` line to commit, so the DCO check passes.
Untested.

fix: Set update-cli commit values and footer for DCO

---

content/blog/2024/10/policy-groups.md

Fix https://github.com/kubewarden/kubewarden.io/issues/262

Add Policy Groups deep dive

---

content/_index.html

<Actions>
<action id="e9a30d07a88d30b0bcb3cf8fadb726f942785e4be12efd5f09365217c8712d66">
<h3>docs: update Kubewarden version on frontpage of kubewarden.io</h3>
<details id="0f38e996c1ef09f6e29d6c8d0b0abd354673a0a1dc199bdc5072beda289e8ad9">
<summary>docs: update Kubewarden with version 1.18</summary>
<p>1 file(s) updated with &#34;&lt;a href=\&#34;#get-started\&#34;&gt;1.18&lt;/a&gt;&#34;:&#xA;&#x9;* content/_index.html&#xA;</p>
<details>
<summary>1.18</summary>
<pre>&#xA;Release published on the 2024-11-04 12:41:46 +0000 UTC at the url https://github.com/kubewarden/kubewarden-controller/releases/tag/v1.18.0&#xA;&#xA;- refactor: simplify wehbook configuration controller handlers (#894)&#xA;- ci: Ensure SLSA Lvl 3 (#904)&#xA;&#xA;## 🚀 Features&#xA;&#xA;- feat: shortName for the CRDs. …

updatecli: docs: update Kubewarden version to 1.18 on front page of kubewarden.io

---

content/blog/2024/12/kubewarden-1-20-release.md

Fix https://github.com/kubewarden/kubewarden.io/issues/286

Add kubewarden-1-20-release blogpost

---

content/blog/2024/12/kubewarden-1-20-release.md

fix OTLM casing, shorten section header

---

content/blog/2024/12/end-year-2024.md

Adds a blog post to share Kubewarden's progress through 2024
Fix #285

feat: End of the 2024 year blog post.

---

config.toml
layouts/partials/header.html

Update kubewarden based on https://github.com/kubewarden/community/issues/33

Move from X to Bluesky & Mastodon

---

config.toml

Follow-up of https://github.com/kubewarden/kubewarden.io/pull/300

Use verified bluesky link

---

content/blog/2025/01/kubewarden-1-21-release.md

Create blog post for 1.21 release, closes https://github.com/kubewarden/kubewarden-controller/issues/988

Add blog post about 1.21.0 release

---

content/blog/2025/02/kubewarden-1-21-1-patch-release.md

Explain what happened, what we've done to fix the issue and to prevent that from happening again

blog post: cover Sigstore incident

---

content/blog/2025/02/beyond-prefix-matching.md

Add new blog post about how kubewarden differentiates from other admission controllers

blog post: beyond prefix matching

---

content/blog/2025/02/kubewarden-1.22-release.md

Fix https://github.com/kubewarden/kubewarden.io/issues/297

feat: Add 1.22 blog post

---

content/_index.html

As part of the work on https://github.com/kubewarden/community/issues/36

Enhance vendor neutrality statement.

---

content/blog/2025/03/kwctl-1-22-1-patch-release.md

Cover the patch release of kwctl.

blog: announce kwctl 1.22.1 release

---

content/blog/2025/03/cncf-webinar-chatloopbackoff.md

Fix https://github.com/kubewarden/kubewarden.io/issues/312

feat: Add webinar blogpost

---

content/blog/2025/03/kubewarden-1.23-release.md

Fixes https://github.com/kubewarden/kubewarden.io/issues/315

blog post: write blog post about the 1.23 release

---

content/blog/2025/03/kubecon-eu-2025.md

Fixes https://github.com/kubewarden/kubewarden.io/issues/318

blog: add entry about KubeCon EU 2025

---

content/blog/2025/04/ingress-nginx-cve-2025-1974.md

How kubewarden can help with [nginx-ingress CVE-2025-1974](https://kubernetes.io/blog/2025/03/24/ingress-nginx-cve-2025-1974/)

blog: add post about nginx-ingress CVE

---

content/blog/2021/06/writing-your-first-policy-with-kubewarden.md
content/blog/2022/07/psp-migration-script.md
content/blog/2022/07/verify-signatures-with-gha-and-prefix.md
content/blog/2022/11/deprecation-policy.md
content/blog/2023/10/audit-scanner-feature.md
content/blog/2023/10/kubewarden-1.8-release.md
content/blog/2024/01/kubewarden-1-10-release.md
content/blog/2024/04/kubewarden-1-12-release.md
content/blog/2024/10/policy-groups.md
content/blog/2024/12/kubewarden-1-20-release.md
content/blog/2025/03/cncf-webinar-chatloopbackoff.md
content/blog/2025/03/kubecon-eu-2025.md

Using the typos tool recently suggested by Klaus.

Typo clean and flush.

---

LICENSE

Adds LICENSE file to make some failing CLOmonitor checks passes.
Related to https://github.com/kubewarden/community/issues/54

chore(clomonitor): add missing LICENSE file.

---

content/blog/2025/04/kubewarden-1.24-release.md

chore: S/bugs/bug fixes

---

config.toml

Currently, the website cannot load the CSS file because the html code
attempts to load it from http, while the site is using https.
This change should fix the issue.

fix: load CSS from https

---

config.toml

Removes the baseURL from file.

fix: remove baseURL from file.

---

content/blog/2025/04/openreport.md

Add a blogpost about Kubewarden participation in OpenReport project
Fix #327

chore: openreports blogpost

---

content/blog/2025/05/kubewarden-1.25-release.md

Adds a blog post to cover the Kubewarden v1.25.0 release.
Fix #342

chore: v1.25.0 release blog post.

---

content/blog/2025/05/adopting-kubewarden.md

This is my blog post to encourage organizations to sign the ADOPTER.md. The idea 
N/A
N/A

initial checkin for blog

---

content/blog/2025/07/kubewarden-1.27-release.md

Adds a blog post to publicize the achievements of the v1.27 release.
Fix #354

feat(release post): add v1.27 release blog post.

---

content/blog/2025/07/kubewarden-1.27.1-release.md

Fix https://github.com/kubewarden/kubewarden.io/issues/358

Add 1.27.1 patch release blog post

---

content/blog/2025/07/gsoc-policy-sdk-js.md

Adds a blog post about Google Summer of Code and Kubewarden's `policy-sdk-js`

Google Summer of Code blog post

---

content/blog/2025/07/kubewarden-1.27.2-release.md

Add blogpost for 1.27.2 kwctl

---

content/blog/2025/07/kubewarden-1.27.3-release.md

Part of https://github.com/kubewarden/kwctl/issues/1318

Add blogpost for Kubewarden 1.27.3 release of kwctl
