content/blog/2021/10/new-architecture-to-ease-kubewarden-administrators-lives.md

Note that the link to release notes is marked as `TODO`, as we haven't
decided on the chart version yet.
[Rendered link](https://github.com/viccuad/kubewarden.io/blob/new-architecture/content/blog/2021/10/new-architecture-to-ease-kubewarden-administrators-lives.md) (image doesn't show)
Closes https://github.com/kubewarden/kubewarden.io/issues/29

Add blog post of new-architecture

---

content/blog/2022/01/mutating-policy-behave-as-validating.md

Adds a new blog post to announce that Kuberwarden has policies which cover all the deprecated Kubernetes PSPs.

Add blog post about the 100% PSP coverage.

---

assets/sass/blog-main.scss
assets/sass/main.scss

Fix the footer icons to the correct colors:
- Run `hugo -D` to generate a build
- View static pages with updated css
The rules for the icons were slightly different for the Blog pages, I fixed both occurrences of the grayscale rules.

Fix footer icons colors

---

CODEOWNERS

Adds the kubewarden-documentation team in the CODEOWNERS file to ensure that they will see all PRs in the repository.

Adds the kubewarden-documentation team in the CODEOWNERS

---

content/blog/2022/03/cri-o-cve-mitigation.md

Adds a blog post showing how users can use Kubewarden to mitigate the CRI-O CVE-2022-0811 blocking Kernel parameters configuration.
Fix #69

CRI-O CVE-2022-0811 mitigation

---

layouts/partials/header.html

Fix #75 
Currently the navigation links are adding the prefix `https://kubewarden.io` to every link, causing each to fail.
- Run `hugo server -D`
- Use navigation links

Fix navigation links - remove relURL from href

---

assets/sass/main.scss
content/_index.html
layouts/partials/header.html

This fixes the issue of the Github button in the main nav disappearing on hover and removes the thematic break above the "Get Started" section.
Fix #77 
`hugo server -D`
View the server at `localhost:1313`

Fix github button hover color - remove thematic break

---

README.md
config.toml

partially fixes https://github.com/kubewarden/kubewarden.io/issues/76
With this, the blog entry is part of the header again:

Show blog in header

---

assets/sass/blog.scss

There were some conflicting styles comeing from the project theme css that caused the unordered lists and list items to be hard to read.
Fix #95 
1. Run `hugo serve`
2. Go to `https://localhost:1313/blog/2022/02/multiplatform-kubewarden/`

Fix conflicting styles with ul and li elements in blog

---

content/blog/2022/05/psp-migration-docs.md

The blog post about PSP migration has link to the old PSP migration documentation page. It has the link for the page before the docusaurus migration. This commit updates the link to the right one.

Fix link to the PSP migration documentation.

---

assets/sass/blog.scss
layouts/blog/list.html

Add a paginator at the bottom of our "all posts" page:
This fixes issue https://github.com/kubewarden/kubewarden.io/issues/112

Add a paginator to our blog

---

content/blog/2022/07/psp-migration-script.md

Fixes a typo in the text of the blog post about PSP migration script.

Fix typo in the PSP migration script text

---

content/blog/2021/09/towards-a-universal-policy-platform.md
content/blog/2021/11/deep-dive-into-policy-logging.md
content/blog/2022/05/monitor-mode.md

Existing links point to `Page Not Found`, removed numbering to fix it.

Fix links: remove obsolete numbering

---

content/blog/2022/11/sigstore-certificate-verification.md
content/blog/2022/12/sigstore-certificate-verification.md

Describe the certificate verification feature.
This fixes https://github.com/kubewarden/kubewarden.io/issues/152
**Important notes:**
* This cannot be merged yet, we have to tag releases of everything
* I think we should do a minor release of the Kubewarden stack. This would make it easier
to our end users to understand which version of Kubewarden is required to leverage this
feature. I don't like the current "required versions" section of the document, it's too
complicated to keep track of everything

Add blog post about certificate verification

---

content/blog/2022/12/community-meeting.md

The date of the community meeting post is wrong. Therefore, when the pages are build the post is not rendered. Changing the date and rebuilding the page fix the issue.
Signed-off-by: José Guilherme Vanz <jguilhermevanz@suse.com>

Fix community meeting post date.

---

config.toml

Remove the link to policy hub from the navigation bar. Replace that with a link to ArtifacHub page that lists all the kubewarden policies.
The navigation bar has now this link: [Policies](https://artifacthub.io/packages/search?kind=13&sort=relevance&page=1). Clicking on the link opens a new browser tab.

fix: remove link to policy hub

---

content/blog/2023/01/release-1_5_0.md

Adds a blog post to announce to the community the Kubewarden v1.5.0 release.
THIS PR SHOULD BE MERGE ONLY AFTER THE v1.5.0 IS PUBLISHED AND THE DOCUMENTATION ABOUT THE POLICY EVALUATION TIMEOUT [PR](https://github.com/kubewarden/docs/pull/164) MERGED.

Kubewarden v1.5.0 release post.

---

content/_index.html

Rancher 2.7.2 [moved to cert-manager 1.11.0](https://github.com/rancher/rancher/releases/tag/v2.7.2)
We still point to cert-manager 1.5.3 in our docs, which is almost 2 years old.

Update cert-manager to 1.11.0

---

content/_index.html
content/blog/2023/09/kubewarden-1.7-release.md

New blog post about kubewarden 1.7 release
Fixes https://github.com/kubewarden/kubewarden.io/issues/189
**Update:** live preview [here](https://deploy-preview-192--moonlit-trifle-c6359f.netlify.app/blog/2023/09/kubewarden-1.7-release/)

Blog post about 1.7 release

---

content/blog/2022/07/psp-migration-script.md

Updates the blog post about the PSP migration script adding a warning about the out of date code snippets in the post. Adding a link to the doc website with the latest documentation.
Fix https://github.com/kubewarden/kubewarden.io/issues/185

fix: add warning message about psp migration code.

---

assets/sass/main.scss
layouts/_default/baseof.html
layouts/partials/survey-banner.html

Fix #204 
This adds the Users Survey as a banner to the main page.
Should we use a few icons to bring attention to the text similar to [Kyverno's github stars banner?](https://kyverno.io/)

Add survey banner to main page

---

.github/workflows/publish.yml

Go back to use the official release of https://github.com/chabad360/hugo-gh-pages instead of our fork.
Our fixes have been merged a long time ago. See https://github.com/chabad360/hugo-gh-pages/pull/21

GH action: stop using a forked action

---

content/_index.html

Upstream docs don't wait via `kubectl wait` anymore (see [here](https://cert-manager.io/docs/installation/kubectl/)), and we know that installing via Helm waits correctly. We are also testing the cert-manager installation via helm, too.
Already using Helm in E2E tests.

Install cert-manager via Helm in first steps

---

config.toml

- Contributes to #144 by updating the GA site ID for the `www` subdomain.
- @jvanz, as I mentioned in https://cncfservicedesk.atlassian.net/browse/CNCFSD-2256, your team will need to make the corresponding updates for the other subdomains, such as `docs`, `charts`, and any other.
- Related issue: #224
- Because of #224, I can already confirm that the new GA4 ID is receiving data 🤷🏼‍♂️ 😄 
- Uses the new GA4 site ID `G-PSW07XK7TM`
/cc @nate-double-u

Use new CNCF Google Analytics 4 (GA4) site ID

---

config-netlify.toml
netlify.toml

Customizes the Netlify build used to preview the website disabling the Google analytics. Therefore, we do not pollute our dashboard with development data.
Fix #224

fix: disable Google analytics when building on Netlify.

---

config.toml
content/_index.html

Fix #218
I have removed the architecture graphic, as discussed in the daily on 2024-05-30.
I have added 'Get started with the latest version - 1.12' in the banner. This links to the 'Get started' section on the same page.
Does that look ok?
I have some questions. 
Do those 'get started instructions' install the latest/current version?
The '1.12' should be updated automatically. I don't know how to do it but `updatecli` may be useful. Does anybody know how to set this up? It appears to be running in the docs repo, but not here. I'll need to get familiar.
So, in Draft, given the questions.
Lastly. Algolia is not being used for this site at the moment, and the change in `config.toml` allowed me to run `hugo server` locally for testing. Otherwise, the build breaks on …

Remove graphic, rearrange page sequence, add link for latest version.

---

.github/workflows/updatecli.yml
content/_index.html
update-compose.yaml
updatecli/updatecli.d/updcli-kw-ver.yml

updatecli for updating the version number on kubewarden.io front page
Adds updatecli config for updating the version number on the front page of kubewarden.io. Also resets to 1.12 as a test. It should be auto PRed by the cron schedule within two hours.
Will close #229 on merge.

updatecli for updating the version number on kubewarden.io front page

---

content/_index.html

PR fixes installation warning:
```
⚠️  WARNING: `installCRDs` is deprecated, use `crds.enabled` instead.
```
Related to https://github.com/kubewarden/docs/pull/427

Update cert manager to support v1.15

---

layouts/partials/footer.html

Remove logos of other projects (some of them CNCF, others Rancher related) from the footer of the page.
This is something CNCF projects should not be doing.

fix: remove logos from footer

---

content/_index.html

- removed `$` since it breaks multiline copy & paste
- removed cert-manager mentions

Remove cert-manager from index page

---

.github/workflows/publish.yml

Removes the usage of the chabad360/hugo-gh-pages Github action. Replacing it with the official Github action to deploy Github pages.
This change means that we will stop deploy the Github pages in a branch and start to use Github environments for that. Which may requires some changes in the repository.
Fix https://github.com/kubewarden/kubewarden-controller/issues/1095

chore: use github actions to deploy github pages.

---

.github/workflows/publish.yml

Remove the hugo cli flag used in the CI to define the baseURL and uses the value defined in the configuration file.

fix: do not define baseURL in CI.
